wxt: additional #include required for MacOS build
After the commit:

commit 35643d86af5f41011723c7363172628283c0b96d
    wxt: release per-thread font data structures before forking

build fails on my Mac (with clang) as:
wxterminal/wxt_gui.cpp:3868:3: error: use of undeclared identifier 'pango_cairo_font_map_set_default'